version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  logstash:
    image: logstash:8.15.2
    container_name: logstash.conf
    volumes:
      - ./logstash.conf/logstash.conf.conf:/usr/share/logstash.conf/pipeline/logstash.conf.conf
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"  # Logstash Beats input
    networks:
      - elk

  kibana:
    image: kibana:8.15.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk

networks:
  elk:
    driver: bridge
